pages:
  before_script:
    - echo "Prepare deployment to ${CI_PAGES_URL}"
    - mkdir public
  script:
    - mv index.yaml public/
    - mv *.tgz public/
    - mv *.tgz-meta/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
